Updated README.md Added provisional endpoints and database schema
fullstacktf/ControlHorarios-Backend pull request #16
Opened 2020-11-04 13:45 UTC by Pandacore

We need to check endpoints and database schema before merge

2020-11-04 15:11 UTC, arianezf approved these changes

2020-11-04 16:02 UTC, AiranSchez approved these changes

2020-11-05 12:08 UTC, jaimerperez approved these changes

2020-11-06 16:20 UTC, yodra commented
Si quieren esto lo revisamos luego en clase

2020-11-09 09:11 UTC, yodra commented
Equipo! no me quedan claros si estos son los unicos endpoints que necesitan.
Por ejemplo no veo nada para fichar (uno de los requisitos del MVP), consultar tus fichajes, horas fichadas diarias o mensuales.. 🤔

2020-11-10 18:20 UTC, AiranSchez requested changes

2020-11-10 18:20 UTC, AiranSchez commented on README.md
> +---
Falta añadir un campo a la tabla Users con el company_name

2020-11-11 12:08 UTC, merged