Workflows
fullstacktf/ControlHorarios-Backend pull request #17
Opened 2020-11-06 15:03 UTC by Pandacore

Actions pass successfully but the containers are not being generated in the droplet.

2020-11-10 12:59 UTC, AiranSchez commented on .github/workflows/deploy.yml
> +  push:
Cambiar para realizarlo cuando hagamos un tag o cuando se haga un merge a la rama main

2020-11-10 13:01 UTC, AiranSchez requested changes
Cambios necesarios

2020-11-10 13:01 UTC, jaimerperez approved these changes

2020-11-11 12:48 UTC, arianezf approved these changes

2020-11-11 15:22 UTC, raulanatol approved these changes

2020-11-12 13:40 UTC, arianezf approved these changes

2020-11-12 13:40 UTC, AiranSchez approved these changes

2020-11-12 13:42 UTC, merged